<?php

namespace mix\task;

use mix\base\BaseObject;

/**
 * 工作者基类
 * @author 刘健 <coder.liu@qq.com>
 */
class BaseWorker extends BaseObject
{

    // 进程对象
    public $worker;

    // 共享内存表
    public $table;

    /**
     * 输入队列
     * @var InputQueue
     */
    public $inputQueue;
    
    /**
     * 输出队列
     * @var OutputQueue
     */
    public $outputQueue;

    // 主进程的PID
    public $masterPid;

    // 工作进程的编号
    public $workerId;

    // 工作进程的PID
    public $workerPid;

    // 初始化事件
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 队列属性赋值
        $this->inputQueue->worker  = $this;
        $this->inputQueue->table   = $this->table;
        $this->outputQueue->worker = $this;
        $this->outputQueue->table  = $this->table;
    }

    // 退出进程
    public function exit()
    {
        $this->worker->exit();
    }

}