<?php
/**
 * Created by PhpStorm.
 * User: Rhilip
 * Date: 2019/6/5
 * Time: 18:47
 *
 * @var League\Plates\Template\Template $this
 * @var string $username
 * @var string $confirm_url
 */
?>

<?php $this->layout('email/layout') ?>

<?php $this->start('username')?><?= $username ?? 'User' ?><?php $this->end();?>

<?php $this->start('subject')?>Recover Confirm<?php $this->end();?>
<?php $this->start('body')?>
You are asking for recover your password in our Site,  <br>
IF this is your action , please click this link to get a new password generated by our system:  <br>

<br>
<a href="<?= $confirm_url ?>" target="_blank"><?= $confirm_url ?></a>
<?php $this->end();?>
