<?php

namespace Rid\Base;

/**
 * 通道类
 */
class Channel extends \Swoole\Coroutine\Channel
{

    /**
     * 抛出数据
     * @return mixed
     * @throws \Throwable
     */
    public function pop($timeout = 0)
    {
        $data = parent::pop($timeout); // TODO: Change the autogenerated stub
        if ($data instanceof \Throwable) {
            throw $data;
        }
        return $data;
    }

}
