<?php

namespace mix\base;

/**
 * 通道类
 * @author 刘健 <coder.liu@qq.com>
 */
class Channel extends \Swoole\Coroutine\Channel
{

    /**
     * 抛出数据
     * @return mixed
     * @throws \Throwable
     */
    public function pop($timeout = 0)
    {
        $data = parent::pop($timeout); // TODO: Change the autogenerated stub
        if ($data instanceof \Throwable) {
            throw $data;
        }
        return $data;
    }

}
