<?php
/**
 * Created by PhpStorm.
 * User: Rhilip
 * Date: 4/29/2020
 * Time: 2020
 */

declare(strict_types=1);

namespace App\Commands\Server;

use Rid\Helpers\ProcessHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class ReloadCommand extends AbstractServerCommand
{
    protected static $defaultName = 'server:reload';

    protected function configure(): void
    {
        $this->setDescription("Reload Swoole HTTP server's workers. It will reload only classes not loaded before server initialization.")
            ->addOption('part', 'p', InputOption::VALUE_OPTIONAL, 'Which Part to be reload', 'worker');
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output);

        $reload_part = $input->getOption('part');
        $sig = $reload_part === 'worker' ? SIGUSR1 : SIGUSR2;

        if ($pid = $this->getPid()) {
            ProcessHelper::kill($pid, $sig);
            $this->io->success('rid-httpd ' . $reload_part . ' process reload completed.');
        } else {
            $this->io->warning('rid-httpd is not running.');
            exit(1);
        }

        return 0; // 返回退出码
    }
}
