<?php
/**
 * Created by PhpStorm.
 * User: Rhilip
 * Date: 4/29/2020
 * Time: 2020
 */

declare(strict_types=1);

namespace App\Commands\Server;

use Rid\Helpers\ProcessHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class ReloadCommand extends AbstractServerStartCommand
{
    protected static $defaultName = 'server:reload';

    protected function configure(): void
    {
        $this->setDescription("Reload Swoole HTTP server's workers. It will reload only classes not loaded before server initialization.")
            ->addOption('part', 'p', InputOption::VALUE_OPTIONAL, 'Which Part to be reload', 'worker');
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output);

        $sig = $input->getOption('part') === 'worker' ? SIGUSR1 : SIGUSR2;

        if ($pid = $this->getPid()) {
            ProcessHelper::kill($pid, $sig);
        }
        if (!$pid) {
            println('rid-httpd is not running.');
            return 1;
        }
        println('rid-httpd ' . ($sig == SIGUSR1 ? 'worker' : 'task') . ' process reload completed.');
        return 0; // 返回退出码
    }
}
