<?php
/**
 * Created by PhpStorm.
 * User: Rhilip
 * Date: 4/29/2020
 * Time: 2020
 */

declare(strict_types=1);

namespace App\Commands\Server;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class StatusCommand extends AbstractServerStartCommand
{
    protected static $defaultName = 'server:status';

    protected function configure(): void
    {
        $this->setDescription('Get Status of Swoole HTTP server');
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
        if ($pid = $this->getPid()) {
            println("rid-httpd is running, PID : {$pid}.");
        } else {
            println('rid-httpd is not running.');
        }
        return 0; // 返回退出码
    }
}
